Repository nextcloud-libraries/nextcloud-vite-config, pull requests merged in 2023-10, with the labels that each got.

#29 fix(lib): Make libconfig work when minification and css split is enabled
  __tests__/libconfig.spec.ts
  lib/libConfig.ts
  package-lock.json
  package.json
Labels: bug, 3. to review

#30 chore(ci): Add test workflow and scripts
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#31 fix(app): Build in app mode and not in lib mode while building Nextcloud apps
  lib/appConfig.ts
  lib/baseConfig.ts
  lib/libConfig.ts
Labels: bug, 3. to review

#32 chore: Prepare release
  .reuse/dep5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#34 fix: Remove `define` of `process.env` from base config
  .gitignore
  .reuse/dep5
  __fixtures__/app_process_env/main.js
  __tests__/__snapshots__/appconfig.spec.ts.snap
  __tests__/appconfig.spec.ts
  lib/baseConfig.ts
Labels: bug, 3. to review

#35 fix(libConfig): import default in CJS build
  lib/libConfig.ts
Labels: bug, 3. to review

#36 chore: Prepare 1.0.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#43 feat(appconfig): Add base path so module preloading works
  lib/appConfig.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#41 feat: add option to customize asset file names
  __tests__/appconfig.spec.ts
  __tests__/libconfig.spec.ts
  lib/appConfig.ts
  lib/baseConfig.ts
  lib/libConfig.ts
Labels: enhancement, 3. to review

#42 fix(appconfig): Fix the default value for inlining CSS
  __tests__/appconfig.spec.ts
  lib/appConfig.ts
Labels: bug, 3. to review

#49 chore: Release 1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
