Repository nextcloud-libraries/nextcloud-vite-config, pull requests merged in 2024-06, with the labels that each got.

#187 chore: update source url in dep5 spec
  .reuse/dep5
Labels: 3. to review, backport-request

#196 chore: Prepare v2.0.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#197 fix: explicitly use window.OC global in app config
  lib/appConfig.ts
Labels: 3. to review, backport-request

#200 chore: Prepare v1.2.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#205 feat(app-config): Add option to override the app name
  __tests__/appconfig.spec.ts
  lib/appConfig.ts
Labels: enhancement, 3. to review, backport-request

#207 Allow to specify an output prefix and load app id from appinfo
  lib/appConfig.ts
  lib/utils/appinfo.ts
Labels: enhancement, 3. to review, backport-request

#204 feat: Add `CSSEntryPointsPlugin` to fix vite for creating one CSS entry per JS entry point
  LICENSES/MIT.txt
  __fixtures__/css-entry-points/first.js
  __fixtures__/css-entry-points/global.css
  __fixtures__/css-entry-points/second.js
  __fixtures__/css-entry-points/shared.css
  __fixtures__/css-entry-points/shared.js
  __tests__/css-entry-points.spec.ts
  lib/appConfig.ts
  lib/plugins/CSSEntryPoints.ts
Labels: bug, 3. to review, backport-request

#211 chore: Prepare v1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#212 chore: Prepare 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#213 chore: Update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
  package-lock.json
  package.json
Labels: 3. to review, backport-request
