Repository nextcloud-libraries/nextcloud-vite-config, pull requests merged in 2024-08, with the labels that each got.

#267 fix: Revert chunkFileNames to include hash
  __tests__/css-entry-points.spec.ts
  lib/appConfig.ts
Labels: bug, 3. to review

#250 feat: Add REUSE license plugin to extract license information for built assets
  lib/appConfig.ts
  lib/plugins/REUSELicensesPlugin.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review, backport-request

#278 chore: Prepare release of v1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#277 chore: Prepare release of v2.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#279 fix: Adjust import of `rollup-plugin-esbuild-minify`
  lib/baseConfig.ts
  package-lock.json
  package.json
Labels: bug, 3. to review, backport-request

#281 chore: Prepare 2.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#282 chore: Prepare 1.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#283 fix(REUSELicensesPlugin): Emit files in `generateBundle` hook to have real filenames
  lib/plugins/REUSELicensesPlugin.ts
Labels: bug, 3. to review, backport-request

#286 chore: Prepare 1.4.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#285 chore: Prepare v2.2.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#293 fix(REUSELicensesPlugin): remove duplicates in license files
  lib/plugins/REUSELicensesPlugin.ts
Labels: bug, 3. to review
