Repository nextcloud-libraries/nextcloud-vite-config, pull requests merged in 2024-01, with the labels that each got.

#93 chore: update workflows from templates
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
Labels: 3. to review, dependencies, automated

#112 fix(css-plugin): Use `generateBundle` hook to prevent CSS imports from being lost
  lib/plugins/ImportCSS.ts
Labels: bug, 3. to review

#116 chore: Prepare release 1.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
